export class ApprovalCenterGrb {

    metroNumber : string;
	grbNumber : string;
	band : string;
	deptCode : string;
	deptName : string;
	requestedBy : string;
	requestedDate : string;
    modifyType : string;
    newMetroNumber: string;
    // grbNum : string;
    // metroNum : string;
    // currentBand : string;
    // reqBand : string;
    // deptCode : string;
    // deptName : string;
    // requestedBy : string;
    // requestedDate : string;
    // lastUpdatedBy : string;
    // hManagerNotesId : string;
    // hManagerId : string; 
    // bandChangeStatus : string; 
    // bizopsComments : string;
    // hManagerComments : string;
    // bizopsUpdateDate : string;
    // filepath : string;
    // resourceType : string;
    // sdl : string;
    // hireType : string;
    // iot : string;
    // location : string;
    // int_grb : string;
    // empId : string;
    // empName : string;
    // empBand : string;
    // empDeptCode : string;
    // empDeptName : string; 
    // ted : string;
    // empStatus : string; 
    // iot_approved_date : string; 
    // sup_name : string;
    // tower : string;
    // sdlmail : string;
    // bizopsremarks : string;
    // action : string;
}
